# Generated by Django 4.0.2 on 2022-02-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=4)),
                ('user_name', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'login_tbl',
            },
        ),
    ]
